package org.glenrockindiancommunity.model;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Family")
public class Family {

    private String id;
    private String familyNameCode;
    private String town;
    private Integer adultCount;
    private Integer childCount;
    private String paymentConfirmationId;
    private List<FamilyMember> familyMembers = new ArrayList<FamilyMember>();;

    Family() {
	// default constructor
    }

    public Family(String familyNameCode, String town, Integer adultCount, Integer childCount) {
	this.familyNameCode = familyNameCode + "-" + UUID.randomUUID().toString().replaceAll("-", "");
	this.town = town;
	this.adultCount = adultCount;
	this.childCount = childCount;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
	return id;
    }

    @DynamoDBAttribute
    public String getFamilyNameCode() {
	return familyNameCode;
    }

    @DynamoDBAttribute
    public String getTown() {
	return town;
    }

    @DynamoDBAttribute
    public Integer getAdultCount() {
	return adultCount;
    }

    @DynamoDBAttribute
    public Integer getChildCount() {
	return childCount;
    }

    @DynamoDBAttribute
    public String getPaymentConfirmationId() {
	return paymentConfirmationId;
    }

    @DynamoDBAttribute(attributeName = "FamilyMembers")
    public List<FamilyMember> getFamilyMembers() {
	return familyMembers;
    }

    public void setId(String id) {
	this.id = id;
    }

    public void setFamilyNameCode(String familyNameCode) {
	this.familyNameCode = familyNameCode;
    }

    public void setTown(String town) {
	this.town = town;
    }

    public void setAdultCount(Integer adultCount) {
	this.adultCount = adultCount;
    }

    public void setChildCount(Integer childCount) {
	this.childCount = childCount;
    }

    public void setPaymentConfirmationId(String paymentConfirmationId) {
	this.paymentConfirmationId = paymentConfirmationId;
    }

    public void setFamilyMembers(List<FamilyMember> familyMembers) {
	this.familyMembers = familyMembers;
    }

    public void addFamilyMember(FamilyMember familyMember) {
	this.familyMembers.add(familyMember);
    }

    public void addFamilyMembers(List<FamilyMember> familyMembers) {
	this.familyMembers.addAll(familyMembers);
    }

}
